In [2]:
import geopandas as gpd
import geohash
import pandas as pd
import numpy as np
import fiona
import json
import shapely
import shapely.geometry
from osgeo import ogr
import requests
import psycopg2
from sqlalchemy import create_engine
import psycopg2
from sqlalchemy import create_engine

In [3]:
boundingbox = gpd.GeoDataFrame.from_file('D:\Datasets\GeoSpatial\gadm_data/gadm36_MYS_2.shp')
boundingbox.head()

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
0,MYS,Malaysia,MYS.1_1,Johor,None,MYS.1.1_1,Batu Pahat,None,None,Daerah,District,None,MY.JH.BP,"POLYGON ((103.00595 1.73628, 103.00550 1.73682..."
1,MYS,Malaysia,MYS.1_1,Johor,None,MYS.1.2_1,Johor Baharu,Johor Bahru,None,Daerah,District,None,MY.JH.JH,"POLYGON ((103.98490 1.43269, 103.98450 1.43238..."
2,MYS,Malaysia,MYS.1_1,Johor,None,MYS.1.3_1,Keluang,Kluang,None,Daerah,District,None,MY.JH.KE,"POLYGON ((103.10678 2.16620, 103.10850 2.16923..."
3,MYS,Malaysia,MYS.1_1,Johor,None,MYS.1.4_1,Kota Tinggi,None,None,Daerah,District,None,MY.JH.KT,"MULTIPOLYGON (((104.05722 1.53083, 104.05750 1..."
4,MYS,Malaysia,MYS.1_1,Johor,None,MYS.1.5_1,Kulaijaya,None,None,Daerah,District,None,MY.JH.KU,"MULTIPOLYGON (((103.55091 1.52211, 103.54640 1..."

In [5]:
kl_selangor_gadm = boundingbox[boundingbox['NAME_1'].isin(['Kuala Lumpur', 'Selangor'])]

In [6]:
print(len(kl_selangor_gadm))

10

In [7]:
kl_selangor_gadm.to_csv('D:\Datasets\MIMOS\kl_selangor_district_boundingbox.csv', index=False)

In [8]:
kl_selangor_gadm.head(20)

,GID_0,NAME_0,GID_1,NAME_1,NL_NAME_1,GID_2,NAME_2,VARNAME_2,NL_NAME_2,TYPE_2,ENGTYPE_2,CC_2,HASC_2,geometry
32,MYS,Malaysia,MYS.4_1,Kuala Lumpur,None,MYS.4.1_1,Kuala Lumpur,None,None,Wilayah Persekutuan,Federal Territory,None,MY.KL.KL,"POLYGON ((101.73227 3.03781, 101.70284 3.03007..."
128,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.1_1,Gombak,None,None,Daerah,District,None,MY.SL.GO,"POLYGON ((101.63429 3.21105, 101.63210 3.20647..."
129,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.2_1,Hulu Langat,Ulu Langat,None,Daerah,District,None,MY.SL.HL,"POLYGON ((101.92247 2.96893, 101.88870 2.89052..."
130,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.3_1,Hulu Selangor,Ulu Selangor,None,Daerah,District,None,MY.SL.HS,"POLYGON ((101.45880 3.39778, 101.46080 3.40378..."
131,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.4_1,Klang,None,None,Daerah,District,None,MY.SL.KE,"MULTIPOLYGON (((101.56800 2.97077, 101.56673 2..."
132,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.5_1,Kuala Langat,None,None,Daerah,District,None,MY.SL.KL,"MULTIPOLYGON (((101.30676 2.89308, 101.30710 2..."
133,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.6_1,Kuala Selangor,None,None,Daerah,District,None,MY.SL.KS,"POLYGON ((101.49320 3.21520, 101.49380 3.19096..."
134,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.7_1,Petaling,Shah Alam,None,Daerah,District,None,MY.SL.PE,"POLYGON ((101.72900 3.00525, 101.72630 3.00249..."
135,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.8_1,Sabak Bernam,None,None,Daerah,District,None,MY.SL.SB,"POLYGON ((101.35710 3.59198, 101.18900 3.53441..."
136,MYS,Malaysia,MYS.15_1,Selangor,None,MYS.15.9_1,Sepang,None,None,Daerah,District,None,MY.SL.SP,"POLYGON ((101.57490 2.97125, 101.57690 2.97424..."